### ISSUE TITLE
screen size

### ISSUE THREAD

**Issue by Perrotn** [ReinhardtBotha/NZXT-aviation#1]
Thank you for sharing your web integration.

I am using a kraken z3 and the display is zoomed in. I suppose you are using a AIO with a larger screen.

The configuration button does not provide any configuration option.

Could you help me with that? 

Thank you

**Comment by ReinhardtBotha** [comment]
Hey, thanks for trying out my web integration! 

My apologies if it is not displaying correctly on your AIO. I made it to display correctly on the Kraken Elite and unfortunately the text is already pretty small on that screen. I'm not sure how it will look on an even smaller screen. 

It doesn't have any configuration at the moment, that's why there are no options showing.

You are welcome to clone my repo and experiment with it yourself to see if you can make it fit on your screen.

**Comment by Jijiooo** [comment]
Hello, i made a branch where i adapted all sizes to the smaller (resolution) NZXT displays. But i can't get it to display, the min HTML file only shows a white page. Even when i download the original repository it shows a white page. How did you host it on https://reinhardtbotha.github.io/NZXT-aviation/. Sorry i'm not a dev only trying things hihi :D

**Comment by ReinhardtBotha** [comment]
Hi @Jijiooo. Did you install the packages and run the dev command in the readme to start the local server? If you do that you will get a local IP address that you can use as the URL for the web integration in CAM.

**Comment by Rqsuku** [comment]
PUMPのRPMだけ０で動きません
ケースファン３にさしてるときは動かないのですか？

**Comment by ReinhardtBotha** [comment]
Readme updated with disclaimer about screen size.
